Show max level tooltip in enchanting table
caoimhebyrne/enchant-tooltips pull request #1
Opened 2024-06-03 20:02 UTC by brunohpaiva

![image](https://github.com/caoimhebyrne/enchant-tooltips/assets/15240571/2cf75737-e9cf-4929-b6f2-fab2819d9496)
![image](https://github.com/caoimhebyrne/enchant-tooltips/assets/15240571/db448c99-26a6-49d1-a44b-2684f2851093)

2024-06-04 12:31 UTC, caoimhebyrne commented
Yeah, that would be good @brunohpaiva

2024-06-04 20:54 UTC, caoimhebyrne commented on src/main/java/dev/caoimhe/enchanttooltips/mixin/EnchantmentScreenMixin.java
> +            .append(")");
Since this is copied from [ItemStackMixin](https://github.com/caoimhebyrne/enchant-tooltips/blob/29b2b392cdee94c734375f20f135b8a3f997919d/src/main/java/dev/caoimhe/enchanttooltips/mixin/ItemStackMixin.java#L70-L82), we could make a generic helper method for it in `dev.caoimhe.enchanttooltips.util.TextUtil`?

```java
package dev.caoimhe.enchanttooltips.util

import net.minecraft.screen.ScreenTexts;
import net.minecraft.text.Text;

public class TextUtil {
    public static Text appendMaximumLevel(Text text, int level) {
        return text
            .copy()
            .append(ScreenTexts.SPACE)
            .append("(")
            .append(Text.translatable("enchant-tooltips.enchantment.maximum_abbreviation"))
            .append(":")
            .append(ScreenTexts.SPACE)
            .append(
                EnchantTooltipsConfig.getInstance().useRomanNumerals
                    ? Text.translatable("enchantment.level." + enchantment.getMaxLevel())
                    : Text.literal(String.valueOf(enchantment.getMaxLevel()))
            )
            .append(")");
    }
}

2024-06-04 20:54 UTC, caoimhebyrne commented on src/main/resources/enchant-tooltips.mixins.json
> +    }
Why the whitespace changes?

2024-06-04 20:54 UTC, caoimhebyrne commented on src/main/java/dev/caoimhe/enchanttooltips/mixin/EnchantmentScreenMixin.java
> +
Remove whitespace @ line 15

2024-06-04 20:54 UTC, caoimhebyrne commented on src/main/java/dev/caoimhe/enchanttooltips/mixin/EnchantmentScreenMixin.java
> +
... and at line 47

2024-06-05 19:35 UTC, brunohpaiva commented on src/main/resources/enchant-tooltips.mixins.json
> +    }
The rest of the file was using 4 spaces, but this specific line was using tabs for some reason

2024-06-06 02:17 UTC, brunohpaiva commented
Split the config into 3 options. Already updated the en_US and pt_BR translations, still need to update the other ones.

2024-06-14 10:47 UTC, caoimhebyrne requested changes
Can you just commit the enchantment table changes w/o the config migration stuff?

So just the `EnchantmentScreenMixin` and `showMaxInEnchantingTable`. I want to move to cloth-config standalone instead of Auto Config, so that might help.

2024-06-14 21:58 UTC, caoimhebyrne approved these changes

2024-06-14 21:59 UTC, merged